import { FC, ReactElement } from 'react';
import Head from "next/head";
import { NavBar } from "../NavBar";
import styles from "./MainLayout.module.css";

interface propsWithChildren {
  children: React.ReactNode
}

export const MainLayout= ({ children }:propsWithChildren): JSX.Element => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>{children}</main>
    </div>
  );
};
